CITIROC_path : ../CitirocControlSoft/bin
HUL_path     : ../hul-common-lib/install/bin
YAML_path    : ../CIRASAME_calib/yaml_files/cirasame013
CIRASAME_ip  : 192.168.2.113
DAC_scan:
  start : 150
  gap   : 3
  steps : 70
FILE_name    : aaa