CITIROC_path : ~/cirasame/CitirocControlSoft/bin
HUL_path     : ~/cirasame/hul-common-lib/install/bin
YAML_path    : ~/cirasame/CIRASAME_calib/yaml_files/cirasameXXX
CIRASAME_ip  : 192.168.2.xxx
DAC_scan:
  start : 150
  gap   : 1
  steps : 450
FILE_name    : aaa